WORLD_BANK_COUNTRY_API_URL = "http://api.worldbank.org/v2/country"
WORLD_BANK_COUNTRY_API_JSON_URL = f"{WORLD_BANK_COUNTRY_API_URL}?format=json"
WORLD_BANK_COUNTRY_API_XML_URL = f"{WORLD_BANK_COUNTRY_API_URL}?format=xml"
